### ISSUE TITLE
Request for Proper Attribution of Copied Code

### ISSUE THREAD

**Issue by Alyetama** [balewgize/background-remover#1]
Dear balewgize,

I am writing to you to bring to your attention that I have recently discovered that you have used [my code](https://github.com/Alyetama/Rembg-Online/blob/main/streamlit_app.py) in your work without proper attribution. As you may know, plagiarism is a serious issue in the open source community, and it is important that we respect each other's intellectual property rights.

I have compared your code with mine, and it is clear to me that you have copied big chunks of my code (excluding the `.gif` processing part). While I am flattered that you found my work useful, I would appreciate it if you could update your work to include the proper attribution.

As the original author of the code, I would like to request that you add a clear and visible attribution in your work, indicating that you have used my code as a reference. This attribution should include my name and the name of the original work. You can include this attribution in the code comments, in the documentation, or on the platform where you published your work.

I believe that it is important that we maintain the integrity of our work and give credit where credit is due. I hope that you can understand my concerns and that we can resolve this matter amicably.

Thank you for your attention, and I look forward to hearing from you soon.

Best regards,
Alyetama

**Comment by balewgize** [comment]
Hi Alyetama, thanks for bringing up your concern.

I just used your code as a reference since I thought everything publicly available on GitHub is meant to be used and modified freely. That is what I understood about open-source projects till now.

But if you need credit for your work, it would be great if you could have mentioned it in the readme so people can understand what needs to be done before using your code as a reference.

I will include credit to your work. If you wish, I can also delete the repo from my profile. Let me know if we can close this issue now. Thanks!

**Comment by Alyetama** [comment]
Thank you for your response. While I understand your perspective on the use of open-source code, it is standard practice to provide proper attribution when using someone else's code. Although my code was not protected by a license at the time you accessed it, I will be adding a license to make it clear how it can be used and what attribution is required. I appreciate your willingness to include a reference to my work, and I think adding the license will help avoid any similar issues in the future. As for deleting the repo, that's entirely up to you. I think we can close this issue now, but please let me know if you have any further questions or concerns.

**Comment by balewgize** [comment]
Okay understood. Thanks for raising the issue in a professional way, appreciate it. I have added your name and link to your GitHub project in the readme.
